HypnoticAlpaca/ImPostr

- .gitignore
- package.json
- server/config/initMiddleware.js
- server/routes/authRoutes.js
- server/routes/platformRoutes.js
- server/server.js
Middleware is applied correctly now
Serving Static Assets
Router in place for all routes (note: endpoint urls have changed slightly)
> Server-side Chores 

- .gitignore
- server/db/dbconnection.js
- server/server.js
Check channel for credentials
Switched to AWS instance of psql
Default database is "thesis", but no tables exist yet since we don't have a solid schema
> Switched to AWS instance of psql

- client/actions/postQueueActions.js
- client/reducers/postQueue.js
- test/reducers/platformListReducerSpec.js
- test/reducers/postQueueReducerSpec.js
switching from testing to worker
> code testing coverage for post queue reducer

- server/db/dbconnection.js
- server/db/users/usercontroller.js
- server/db/users/usermodel.js
- server/routes/authRoutes.js
User Model and Controller now fully support Login and Signup Reads/Writes to the deployed DB.
> User Model and Controller

- package.json
- server/users/user.model.js
- server/users/util.js
Initial setup for re-model and bcrypt utilities
> Initial user model re-model and bcrypt util

- Dockerrun.aws.json
> Dockeraws.run.json appended

- client/actions/postQueueActions.js
- client/components/Login.js
- client/components/Signup.js
- client/containers/App.js
- client/containers/PostQueueContainer.js
- client/reducers/postQueue.js
- server/posts/post.controller.js
- server/posts/post.routes.js
post controller now correctly sends db queue to client
client correctly renders queue
> post controller

- client/components/PlatformListEntry.js
- server/auth/authcontroller.js
AuthRoutes on Buttons
Team just needs to work on endpoints
> AuthRoutes on Buttons now

- server/config/sequelize.js
> Sequelize Addition

- .gitignore
- server/config/config.js
- server/platformservices/linkedin.js
Base for microservices (eventually), but housed in the main server for now
> Setting up Platform Services

- server/platformservices/linkedin.js
LinkedIn Methods in place now
Should be usable by worker
> LinkedIn Methods for posting user queue

- client/components/Login.js
- client/index.html
- client/index.js
- client/style/style.css
- package.json
Material-UI passed into App component in index.js
Working on Auth (Signup/Login) components right now
> CSS initialization with Material UI

- client/components/Login.js
- client/components/Signup.js
- client/components/Splash.js
- client/containers/Auth.js
- client/index.html
- client/style/style.css
- Mimics the splash sign up / log in centerpiece
- Justin will bring it home with a great image in the background
> Mimic Slack CSS for Splash Signup and Login functionality

- .gitignore
- server/posts/post.controller.js
- server/posts/post.model.js
- server/posts/post.routes.js
post history framework should be functioning from the server-side
routes/controller working
> Post history framework

- client/actions/UserLoginActions.js
- client/actions/historyListActions.js
- client/components/HistoryList.js
- client/components/HistoryListItem.js
- client/components/Home.js
- client/containers/App.js
- client/containers/HistoryListContainer.js
- client/reducers/historyListReducers.js
- client/reducers/reducers.js
- server/posts/post.controller.js
History List v0 is now functional
Pulls correctly only from message, platform, and post date.  When posts table is updated, we may need to update render properties, but it's functional for now.
> History List v0

- server/posts/post.controller.js
Minor fix to getExpiredActive and destroying posts
> Minor fix to getExpiredActive and destroying posts

- .dockerignore
- client/actions/UserLoginActions.js
- client/actions/addNewPostActions.js
- client/actions/historyListActions.js
- client/actions/platformListActions.js
- client/actions/postQueueActions.js
- client/components/Footer.js
- client/components/Navbar.js
- client/components/PlatformListEntry.js
- server/lnkdMicro/external.go
- server/lnkdMicro/handlers.go
- server/lnkdMicro/main.go
- server/lnkdMicro/routes.go
Fixed Links on Front-End to ensure parity with deployment
> Chores frontendlinks

- README.md
ReadMe with improved English and descriptions (directions only)
> ReadME updated for docker use

- client/actions/UserLoginActions.js
- client/components/App.js
- client/containers/AppContainer.js
- client/reducers/UserLoginReducers.js
Solved the problem with Login Page flashing temporarily while JWT was validated
Async problems solved!
> Solved problem with JWTFailure

- client/reducers/UserLoginReducers.js
Last minute fix to requestStart not being invoked
> Last minute fix to requestStart not being invoked
